name: Process Music Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install marked dompurify jsdom axios

    - name: Check if issue title contains [MUSIC]
      uses: actions/github-script@v7
      with:
        script: |
            const issueTitle = context.payload.issue.title;
            if (issueTitle.includes("[MUSIC]")) {
              core.exportVariable('IS_MUSIC_ISSUE', 'true');
            } else {
              core.exportVariable('IS_MUSIC_ISSUE', 'false');
            }

    - name: Stop if not a music issue
      if: env.IS_MUSIC_ISSUE == 'false'
      run: echo "Not a music issue. Skipping further steps."

    - name: Check for YouTube link in issue body
      if: env.IS_MUSIC_ISSUE == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const issueBody = context.payload.issue.body;
          const youtubeLink = issueBody.match(/https:\/\/www.youtube.com\/watch\?v=([\w-]+)/);
          if (youtubeLink) {
            core.exportVariable('HAS_YOUTUBE_LINK', 'true');
            core.exportVariable('YOUTUBE_ID', youtubeLink[1]);
          } else {
            core.exportVariable('HAS_YOUTUBE_LINK', 'false');
          }

    - name: Display YouTube link check result
      if: env.IS_MUSIC_ISSUE == 'true'
      run: |
          echo "Contains YouTube link: ${{ env.HAS_YOUTUBE_LINK }}"

    - name: Escape issue body for JSON
      if: env.HAS_YOUTUBE_LINK == 'true' && env.IS_MUSIC_ISSUE == 'true'
      uses: actions/github-script@v7
      with:
        script: |
              const marked = require('marked');
              const DOMPurify = require('dompurify')(new (require('jsdom').JSDOM)().window);
              const { JSDOM } = require('jsdom');
    
              function markdownToJsonSafeString(markdownContent) {
                  // Convert markdown to HTML
                  const htmlContent = marked.parse(markdownContent);
    
                  // Sanitize the HTML content
                  const sanitizedHtmlContent = DOMPurify.sanitize(htmlContent);
    
                  // Use jsdom to create a temporary DOM element to extract text content from sanitized HTML
                  const dom = new JSDOM(sanitizedHtmlContent);
                  const textContent = dom.window.document.body.textContent || '';
    
                  // Ensure the text content is JSON-safe
                  const jsonSafeString = JSON.stringify(textContent);
    
                  return jsonSafeString;
              }
    
              const issueBody = context.payload.issue.body;
              const escapedIssueBody = markdownToJsonSafeString(issueBody);
              core.exportVariable('ESCAPED_ISSUE_BODY', escapedIssueBody);

    - name: Extract and display YouTube ID if link is found
      if: env.HAS_YOUTUBE_LINK == 'true' && env.IS_MUSIC_ISSUE == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          const { YOUTUBE_ID, ESCAPED_ISSUE_BODY } = process.env;
          const system = `Imagine three different data experts are answering this task. All experts will write down 1 step of their thinking, then share it with the group. Then all experts will go on to the next step, etc. If any expert realizes they're wrong at any point then they leave. Please read the provided text, extract the required information, sanitize the title, and fill it into the specified command format. The title should only contain numbers, letters, spaces, and the characters () . and -.\n\n**Example:**\n\`\`\`\n\n**Fill out the Form**\n\nYouTube Link: https://www.youtube.com/watch?v=<yt_id>\nTitle:  <title> \nGenre:  <genre>\n\nPick only one of the different genres!\ndnb, chillstep, lofihiphop, nujazz, electroswing, edm, rock\n\n\n\`\`\`\n\n**Output:**\n\n\`\`\`bash\n./kbve.sh -nx kbve.com:music --args=\\\"--file=lofihiphop --title='Hippie Sabotage - The Best of Chill Music (Mix)' --ytid=ODXq4FtS-ys\\\"\"\n\nHere is the template for the command:\n\`\`\`\n./kbve.sh -nx kbve.com:music --args=\\\"--file=[insert file/genre here] --title='[insert sanitized title here]' --ytid=[insert YouTube ID here]\\\"\n\nEnsure to:\n1. Extract the \`File/Genre\`, \`Title\`, and \`YouTube ID\` from the text.\n2. Sanitize the \`Title\` to only include numbers, letters, and the characters () . and -.\n3. Only acceptable genres/file are dnb, chillstep, lofihiphop, nujazz, electroswing, edm, rock\n4. Fill in the command template with the extracted and sanitized values.\n\n**Your Task:**\nPlease parse the provided text below and generate the command.\n\n`;
          const message = ESCAPED_ISSUE_BODY;

          const payload = JSON.stringify({
            system,
            message,
            model: "llama3-8b-8192"
          });

          const axios = require('axios');
          const response = await axios.post('https://rust.kbve.com/api/v1/call_groq', payload, {
            headers: {
              'Content-Type': 'application/json'
            }
          });
          core.exportVariable('GROQ_OUTPUT', response.data);

    - name: Post debug comment to issue
      if: env.HAS_YOUTUBE_LINK == 'true' && env.IS_MUSIC_ISSUE == 'true'
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const { GROQ_OUTPUT } = process.env;
          const issue_number = context.issue.number;
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: `Here is the JSON processed information:\n\n\`\`\`json\n${GROQ_OUTPUT}\n\`\`\``
          });

    - name: Post shell command to issue
      if: env.HAS_YOUTUBE_LINK == 'true' && env.IS_MUSIC_ISSUE == 'true'
      uses: actions/github-script@v7
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        script: |
          const { GROQ_OUTPUT } = process.env;
          const output = JSON.parse(GROQ_OUTPUT);
          const messageContent = output.choices[0].message.content;

          const shellCommandMatch = messageContent.match(/```bash\n([\s\S]*?)\n```/);
          const shellCommand = shellCommandMatch ? shellCommandMatch[1] : 'No shell command found';

          if (shellCommandMatch) {
            core.exportVariable('HAS_SHELL_COMMAND', 'true');
          }

          const issue_number = context.issue.number;
          const repo = context.repo.repo;
          const owner = context.repo.owner;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: `Here is the shell command extracted from the message:\n\n\`\`\`bash\n${shellCommand}\n\`\`\``
          });
